### ISSUE TITLE
libadd_path.so does not work in bash or zsh

### ISSUE THREAD

**Issue by 0x5457** [NexusGPU/tensor-fusion#164]
## Describe the bug
When using a Kubernetes pod with a command like:
```yaml
env:
  - name: LD_PATH
    value: /tensor-fusion
  - name: LD_PRELOAD
    value: /tensor-fusion/libadd_path.so:/tensor-fusion/libcuda.so
command:
  - bash
  - '-c'
  - 'echo $PATH'
```

The expected behavior is to see `/tensor-fusion` in the output of `echo $PATH`, but this does not happen.

However, when replacing `bash` with `sh` in the pod definition, the `LD_PRELOAD` environment variable works as expected.

### Steps to reproduce

Use the `bash` in the command.

### Expected behavior
Should see `/tensor-fusion` in the output of `echo $PATH`.

### Environment
 - OS: [ubuntu 24.04]
