### ISSUE TITLE
Add GPU Model Support for Resource Allocation

### ISSUE THREAD

**Issue by 0x5457** [NexusGPU/tensor-fusion#187]
## Overview
Currently tensor-fusion supports GPU allocation through annotations, but lacks the ability to specify GPU model types (like A100, H100). This feature will add support for model-specific GPU requests.

## Feature Description
Allow users to request specific GPU models through a new annotation in tensor-fusion deployments.

### New Annotation
```yaml
tensor-fusion.ai/gpu-model: "A100"  # Supports A100, H100, etc.
```

### Example Usage
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch-test
  namespace: tensor-fusion
spec:
  template:
    metadata:
      labels:
        tensor-fusion.ai/enabled: "true"
      annotations:
        tensor-fusion.ai/gpu-model: "A100"
        tensor-fusion.ai/gpupool: "shared-tensor-fusion-cluster-shared"
        tensor-fusion.ai/vram-request: "1Gi"
        ...
```

## Technical Implementation
1. Add new GPU model filter in `/pkg/filter/` package
2. Extend webhook to handle new annotation
3. Update resource allocation logic to consider GPU model constraints

## Acceptance Criteria
- [ ] Support for `tensor-fusion.ai/gpu-model` annotation
- [ ] Proper validation of GPU model values
- [ ] Resource allocation respects GPU model constraints

## Notes
- Optional annotation for backward compatibility
- Invalid model specifications will be rejected
